name: 'snowflake_env_setup'
version: '0.0.1'

config-version: 2

require-dbt-version: ">=1.0.0"

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]
log-path: "logs"
target-path: "target"
clean-targets: ["data/target", "data/packages"]
