name: 'snowflake_setup'
version: '0.0.1'

config-version: 2

require-dbt-version: ">=0.17.0"


macro-paths: ["macros"]
test-paths: ["tests"]
log-path: "logs"
target-path: "target"
clean-targets: ["data/target", "data/packages"]
